-- MySQL Script generated by MySQL Workbench
-- Mon May  4 08:16:06 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema loja_ihs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loja_ihs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja_ihs` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `loja_ihs` ;

-- -----------------------------------------------------
-- Table `loja_ihs`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_ihs`.`categorias` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(100) NULL DEFAULT NULL,
  `DataCad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_ihs`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_ihs`.`clientes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Cpf` CHAR(11) NOT NULL,
  `DataCad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Cpf` (`Cpf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_ihs`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_ihs`.`enderecos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdCliente` INT NOT NULL,
  `Cep` CHAR(8) NOT NULL,
  `Logradouro` VARCHAR(100) NOT NULL,
  `Numero` VARCHAR(10) NOT NULL,
  `Bairro` VARCHAR(50) NOT NULL,
  `Cidade` VARCHAR(50) NOT NULL,
  `Estado` CHAR(100) NOT NULL,
  `Complemento` VARCHAR(100) NULL DEFAULT NULL,
  `DataCad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  INDEX `IdCliente` (`IdCliente` ASC) VISIBLE,
  CONSTRAINT `enderecos_ibfk_1`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `loja_ihs`.`clientes` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_ihs`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_ihs`.`pedidos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ClienteId` INT NOT NULL,
  `SubTotal` DECIMAL(18,2) NOT NULL,
  `Status` ENUM('Aberto', 'Finalizado', 'Pendente') NOT NULL,
  `DataCad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`, `ClienteId`),
  INDEX `FK_clientes_pedidos` (`ClienteId` ASC) VISIBLE,
  CONSTRAINT `FK_clientes_pedidos`
    FOREIGN KEY (`ClienteId`)
    REFERENCES `loja_ihs`.`clientes` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_ihs`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_ihs`.`produtos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdCategoria` INT NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Valor` DECIMAL(10,2) NOT NULL,
  `CaminhoImagem` VARCHAR(255) NULL DEFAULT NULL,
  `DataCad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  INDEX `IdCategoria` (`IdCategoria` ASC) VISIBLE,
  CONSTRAINT `produtos_ibfk_1`
    FOREIGN KEY (`IdCategoria`)
    REFERENCES `loja_ihs`.`categorias` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_ihs`.`itempedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_ihs`.`itempedidos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `PedidoId` INT NOT NULL,
  `ProdutoId` INT NOT NULL,
  `Quantidade` DECIMAL(18,2) NOT NULL,
  `ValorItem` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`Id`, `PedidoId`, `ProdutoId`),
  INDEX `fk_itens_pedido_pedidos` (`PedidoId` ASC) VISIBLE,
  INDEX `FK_itensPedidos_produtos` (`ProdutoId` ASC) VISIBLE,
  CONSTRAINT `fk_itens_pedido_pedidos`
    FOREIGN KEY (`PedidoId`)
    REFERENCES `loja_ihs`.`pedidos` (`Id`),
  CONSTRAINT `FK_itensPedidos_produtos`
    FOREIGN KEY (`ProdutoId`)
    REFERENCES `loja_ihs`.`produtos` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_ihs`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_ihs`.`telefones` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdCliente` INT NOT NULL,
  `Numero` VARCHAR(15) NOT NULL,
  `DataCad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  INDEX `IdCliente` (`IdCliente` ASC) VISIBLE,
  CONSTRAINT `telefones_ibfk_1`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `loja_ihs`.`clientes` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
